# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if Gem::Version.new('13.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end

target 'Bowfolios-trigeeks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bowfolios-trigeeks
# Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
  # Pods for Bowfolios-trigeeks

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'SDWebImageSwiftUI'
pod 'FirebaseFirestoreSwift'

end
